<?php if (defined('AAM_KEY')) { ?>
    <div class="row">
        <div class="col-xs-12">
            <p class="aam-info">
                <?php echo AAM_Backend_View_Helper::preparePhrase('Managing default access to categories (terms) is available in [AAM Plus Package] only. But you can still manage access to individual posts, pages or custom post types. Consider to purchase [AAM Plus Package] extension.', 'b', 'b'); ?>
            </p>
            
            <img src="http://vasyltech.com/img/aam-term-access-form.jpg" class="img-responsive" />
        </div>
    </div>
<?php
}