<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="metabox-content">
        <div class="row<?php echo ($this->isOverwritten() ? '' : ' hidden'); ?>">
            <div class="col-xs-12">
                <div class="aam-overwrite">
                    <span><i class="icon-attention-circled"></i> <?php echo __('Settings may not be inherited', AAM_KEY); ?></span>
                    <span><a href="#" id="metabox-reset"><?php echo __('Reset', AAM_KEY); ?></a>
                </div>
            </div>
        </div>

        <div class="aam-feature-top-actions text-right">
            <a href="#" class="btn btn-xs btn-primary" id="refresh-metabox-list"><i class="icon-arrows-cw"></i> <?php echo __('Refresh', AAM_KEY); ?></a>
        </div>

        <?php 
            global $wp_post_types;
            
            $first       = false;
            $object      = AAM_Backend_View::getSubject()->getObject('metabox');
            $metaboxList = $this->getMetaboxList(); 
        ?>

        <?php if (!empty($metaboxList)) { ?>
            <div class="panel-group" id="metabox-list" role="tablist">
                <?php foreach ($metaboxList as $screen => $metaboxes) { ?>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="group-<?php echo $screen; ?>-heading">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#metabox-list" href="#group-<?php echo $screen; ?>" aria-controls="group-<?php echo $screen; ?>" <?php if (!$first) { echo 'aria-expanded="true"'; } ?>>
                                    <?php
                                    switch ($screen) {
                                        case 'dashboard':
                                            echo __('Dashboard Widgets', AAM_KEY);
                                            break;

                                        case 'widgets':
                                            echo __('Frontend Widgets', AAM_KEY);
                                            break;

                                        default:
                                            echo $wp_post_types[$screen]->labels->name;
                                            break;
                                    }
                                    ?>
                                </a>
                            </h4>
                        </div>
                        <div id="group-<?php echo $screen; ?>" class="panel-collapse collapse<?php if (!$first) { echo ' in'; $first = true; } ?>" role="tabpanel" aria-labelledby="group-<?php echo $screen; ?>-heading">
                            <div class="panel-body">
                                <div class="row aam-bordered">
                                    <?php foreach ($metaboxes as $metabox) { ?>
                                        <div class="col-xs-12 col-md-6 aam-submenu-item">
                                            <label for="metabox-<?php echo $screen; ?>-<?php echo $metabox['id']; ?>"><?php echo $metabox['title']; ?></label>
                                            <input type="checkbox" class="aam-checkbox-danger" id="metabox-<?php echo $screen; ?>-<?php echo $metabox['id']; ?>" data-metabox="<?php echo $screen; ?>|<?php echo $metabox['id']; ?>"<?php echo ($object->has($screen, $metabox['id']) ? ' checked="checked"' : ''); ?> />
                                            <label for="metabox-<?php echo $screen; ?>-<?php echo $metabox['id']; ?>"></label>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } else { ?>
            <div class="row">
                <div class="col-xs-12 text-center">
                    <p class="aam-notification-message"><?php echo __('The list of metaboxes and widgets is not initialized. Click Refresh button above.'); ?></p>
                </div>
            </div>
        <?php } ?>
    </div>
<?php
}