<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="contact-content">
        <div class="row">
            <div class="col-xs-12">
                <p class="aam-info">
                    <?php echo __('Feel free to contact us if you have any questions or concerns but follow few simple rules:'); ?>
                </p>
                <ol class="text-larger">
                    <li>Keep your message short. As longer message as longer it will take for us to response;</li>
                    <li>Use English, Polish, Russian or Ukrainian language. Otherwise we may ignore your message;</li>
                    <li>You can hire us to do some custom functionality for your needs but please be clear with your requirements;</li>
                    <li>In case of issues with the plugin, if possible, include screenshots or videos that show the problem;</li>
                    <li>Be patient. It might take up to 3 business days for us to response.</li>
                </ol>
                <h3 class="aam-info text-center">
                    e-mail: vasyl@vasyltech.com
                </h3>
            </div>
        </div>
    </div>
    <?php
}