<?php if (defined('AAM_KEY')) { ?>
    <div class="wrap">
        <div class="row">
            <div class="col-xs-12 col-md-8">
                <h1 class="aam-current-subject"></h1>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-8">
                <div class="metabox-holder">
                    <div class="postbox">
                        <h3 class="hndle">
                            <span><?php echo __('Access Control Panel', AAM_KEY); ?></span>
                            <span class="aam-help-menu" data-target="#access-manager-inside"><i class="icon-help-circled"></i></span>
                        </h3>
                        <div class="inside" id="access-manager-inside">
                            <div class="aam-postbox-inside" id="aam-content"></div>
                            <div class="aam-help-context" >
                                <div class="text-justify aam-large-padding">
                                    <p class="text-larger"><?php echo __('Appreciate your interest in Advanced Access Manager (aka AAM). With strong knowledge and experience in WordPress, AAM becomes a very powerful tool to manage access to your frontend and backend.', AAM_KEY); ?></p>
                                    <p class="text-larger"><span class="aam-highlight"><?php echo __('Please notice!', AAM_KEY); ?></span> <?php echo AAM_Backend_View_Helper::preparePhrase('Power comes with responsibility. Make sure that you have enough knowledge in WordPress Roles & Capabilities because AAM is very closely intergrated with WordPress core. It is also very important [to have backup of your database before you start working with AAM] (there is no need to backup your files, AAM does not modify any physical files on your server and never did).', 'b'); ?></p>
                                    <p class="text-larger"><?php echo __('AAM was thoroughly tested on the fresh installation of WordPress and in the latest versions of Chrome, Safari, IE and Firefox. If you have any issues, the most typical case is the conflict with other plugins or themes.', AAM_KEY); ?></p>
                                    <p class="text-larger"><?php echo sprintf(__('Also check our %sIntroduction to AAM%s so you know where to start.', AAM_KEY), '<a href="http://vasyltech.com/blog/introduction-to-aam" target="_blank">', '</a>'); ?></p>
                                </div>
                                
                                <div class="aam-info aam-social">
                                    <a target="_blank" href="http://vasyltech.com/advanced-access-manager"><i class="icon-home"></i></a>
                                    <a target="_blank" href="http://twitter.com/vasyltech"><i class="icon-twitter"></i></a>
                                    <a target="_blank" href="https://github.com/VasylTech/advanced-access-manager"><i class="icon-github"></i></a>
                                    <a target="_blank" href="https://www.facebook.com/vasyltech"><i class="icon-facebook"></i></a>
                                    <a target="_blank" href="https://wordpress.org/support/view/plugin-reviews/advanced-access-manager"><i class="icon-star"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-4">
                <?php if (AAM_Core_Console::hasIssues()) { ?>
                <div class="metabox-holder">
                    <div class="postbox">
                        <h3 class="hndle text-danger">
                            <i class='icon-attention-circled'></i> <span><?php echo __('Notifications', AAM_KEY); ?></span>
                        </h3>
                        <div class="inside">
                            <div class="aam-postbox-inside">
                                <ul class="aam-error-list">
                            <?php foreach (AAM_Core_Console::getWarnings() as $message) { ?>
                                <li><?php echo $message; ?></li>
                            <?php } ?>
                        </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>
                <div class="metabox-holder">
                    <?php do_action('aam-sidebar-ui-action', 'top'); ?>

                    <div class="postbox">
                        <h3 class="hndle">
                            <span><?php echo __('User/Role Panel', AAM_KEY); ?></span>
                            <span class="aam-help-menu" data-target="#user-role-manager-inside"><i class="icon-help-circled"></i></span>
                        </h3>
                        <div class="inside" id="user-role-manager-inside">
                            <div class="aam-postbox-inside">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li role="presentation" class="active"><a href="#roles" aria-controls="roles" role="tab" data-toggle="tab"><i class="icon-users"></i> <?php echo __('Roles', AAM_KEY); ?></a></li>
                                    <li role="presentation"><a href="#users" aria-controls="users" role="tab" data-toggle="tab"><i class="icon-user"></i> <?php echo __('Users', AAM_KEY); ?></a></li>
                                    <li role="presentation"><a href="#visitor" aria-controls="visitor" role="tab" data-toggle="tab"><i class="icon-user-secret"></i> <?php echo __('Visitor', AAM_KEY); ?></a></li>
                                </ul>
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane active" id="roles">
                                        <table id="role-list" class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Users</th>
                                                    <th width="70%"><?php echo __('Role', AAM_KEY); ?></th>
                                                    <th><?php echo __('Action', AAM_KEY); ?></th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>

                                        <div class="modal fade" id="add-role-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Create Role', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label for="new-role-name"><?php echo __('Role Name', AAM_KEY); ?><span class="aam-asterix">*</span></label>
                                                            <input type="text" class="form-control" id="new-role-name" placeholder="<?php echo __('Enter Role Name', AAM_KEY); ?>" />
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="inherit-role-list"><?php echo __('Inherit Capabilities From', AAM_KEY); ?></label>
                                                            <select class="form-control" id="inherit-role-list">
                                                                <option value=""><?php echo __('Select Role', AAM_KEY); ?></option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-success" id="add-role-btn"><?php echo __('Create', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="modal fade" id="edit-role-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Update Role', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label for="new-role-name"><?php echo __('Role Name', AAM_KEY); ?></label>
                                                            <input type="text" class="form-control" id="edit-role-name" placeholder="<?php echo __('Enter Role Name', AAM_KEY); ?>" />
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-success" id="edit-role-btn"><?php echo __('Update', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="modal fade" id="delete-role-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Delete Role', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-center aam-confirm-message" data-message="<?php echo __('Are you sure that you want to delete %s role?', AAM_KEY); ?>"></p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-danger" id="delete-role-btn"><?php echo __('Delete', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="modal fade" id="role-notification-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Notification', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-larger"><?php echo __('You are not allowed to delete this role because either you do not have a capability to "delete_users" or there is at least one user assigned to it.', AAM_KEY); ?></p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('OK', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="users">
                                        <table id="user-list" class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Roles</th>
                                                    <th width="65%"><?php echo __('Username', AAM_KEY); ?></th>
                                                    <th><?php echo __('Action', AAM_KEY); ?></th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>

                                        <div class="modal fade" id="user-notification-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Notification', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-center aam-notification-message"><?php echo __('You are not allowed to perform this action.', AAM_KEY); ?></p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('OK', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="visitor">
                                        <div class="visitor-message">
                                            <span class="aam-bordered"><?php echo __('Manage access to your website for visitors (any user that is not authenticated)', AAM_KEY); ?>.</span>
                                            <button class="btn btn-primary btn-block" id="manage-visitor"><i class="icon-cog"></i> <?php echo __('Manage Visitors', AAM_KEY); ?></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="aam-help-context">
                                <p class="aam-info aam-hint">
                                    <?php echo AAM_Backend_View_Helper::preparePhrase('Manage access for your users, roles and visitors. Be careful with [Administrator] role as well as your admin user. [Database backup is strongly recommended].', 'b', 'b'); ?>
                                </p>

                                <p class="text-justify">
                                    <strong><i class="icon-users"></i> <?php echo __('Roles', AAM_KEY); ?></strong><br/>
                                    <?php echo __('With Roles tab you can manage access for any defined role, edit role\'s name, create new role or even delete existing (but only when there is no users assigned to it). You are not allowed to delete Administrator role.', AAM_KEY); ?>
                                </p>

                                <p class="text-justify">
                                    <strong><i class="icon-user"></i> <?php echo __('Users', AAM_KEY); ?></strong><br/>
                                    <?php echo __('Manage access for any user. As a bonus feature, you can block user. It means that user will be not able to login to your website anymore.', AAM_KEY); ?>
                                </p>

                                <p class="text-justify">
                                    <strong><i class="icon-user-secret"></i> <?php echo __('Visitor', AAM_KEY); ?></strong><br/>
                                    <?php echo __('Visitor can be considered any user that is not authenticated to your website.', AAM_KEY); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <?php do_action('aam-sidebar-ui-action', 'bottom'); ?>
                </div>
            </div>
        </div>
    </div>
    <?php
}